---
name: policy
on:
  pull_request:
  push:
    branches:
    # This is run on merge queue branches as there are jobs listed in this
    # action that are often required in branch protection rules. Due to guards
    # below certain jobs may not run in merge queue branches but will still
    # return a status indicating a pass.
    - gh-readonly-queue/**
    - master
jobs:
  check-merge-commits:
    if: github.event_name == 'pull_request'
    name: Check merge commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git config --global --add safe.directory /github/workspace
        merge_commits=$(git rev-list --merges "origin/$GITHUB_BASE_REF".."origin/$GITHUB_HEAD_REF")
        if [ -n "$merge_commits" ]; then
          echo "Error: merge commits found in $GITHUB_BASE_REF..$GITHUB_HEAD_REF"
          for merge_commit in $merge_commits; do
            echo "$merge_commit"
          done
          exit 1
        fi
  commit-message-style:
    if: github.event_name == 'pull_request' && github.triggering_actor != 'dependabot[bot]'
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 19.x
    - name: Install base config
      run: npm install @commitlint/config-conventional
    - name: Validate all commits
      run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD --verbose
  terraform:
    name: Check Terraform configuration formatting
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
    - run: terraform fmt -check -recursive
  tfsec:
    name: Scan Terraform code for security vulnerabilities
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        github_token: ${{ github.token }}
  yamllint:
    name: Lint YAML documents
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install yamllint
      run: pip install --user yamllint
    - name: Lint
      run: yamllint .
